title: Sushant Bagul
logo: "/Sushant.png"
description: >
  <br>
  Java Developer | Cloud Enthusiast
  <br>
  <a href="https://www.linkedin.com/in/sushant-bagul">
    <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?&style=for-the-badge&logo=linkedin&logoColor=white">
  </a>
  <a href="mailto:bagulsushant.sit.it@gmail.com">
    <img alt="Gmail" src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" />
  </a>
theme: jekyll-theme-minimal
